package:
  name: cloudmesh.common
  version: 1

source:
  url: https://github.com/cloudmesh/cloudmesh.common.git
  sha256: d58439c548433adcda98e695be53e526ba940a4b9c44fb9a05d92cd495cdd47f
  

build:
  number: 0
  
requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - cloudmesh.common
